version: "0.2"
ignorePaths:
  - "**/*.uid"
  - "**/*.import"
  - export_presets.cfg
  - build/**
  - .godot/**
dictionaryDefinitions:
  - name: cucciolo-dictionary
    path: ./.cspell/cucciolo-dictionary.txt
    addWords: true
dictionaries:
  - cucciolo-dictionary
  - game-development
  - shellscript
  - fonts
  - cpp-compound-words
words: []
ignoreWords: []
import: []
overrides:
  - filename: "**/*.tres"
    ignoreRegExpList:
      - /"(?:[0-9]+_[a-z0-9]+|Resource_[a-z0-9]+)"/g
