version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: cucciolo-dictionary
    path: ./.cspell/cucciolo-dictionary.txt
    addWords: true
dictionaries:
  - cucciolo-dictionary
words: [cucciolo, mando]
ignoreWords: []
import: []
