version: "0.2"
ignorePaths:
  - "**/*.uid"
dictionaryDefinitions:
  - name: cucciolo-dictionary
    path: ./.cspell/cucciolo-dictionary.txt
    addWords: true
dictionaries:
  - cucciolo-dictionary
  - game-development
  - shellscript
  - fonts
  - cpp-compound-words
words:
  - cucciolo
  - mando
  - chefalmando
  - chefalmandodev
ignoreWords: []
import: []
